variables:
  - group: vh-wowza
  - group: vh-infra-dev
  - group: vh-infra-prod

trigger:
  branches:
    include:
    - master
    - release/*
    - hotfix/*

pr:
  branches:
    include:
    - master

stages:
  - template: pipeline/vh-terraform.yml
    parameters:
      deploymentResource: vh_wowza
      serviceConnections:
        arm: $(infra_arm_service_connection)
        dns: $(infra_arm_service_connection_prod)
      tf_params:
        dns_tenant_id: $(dns_Tenant_Id)
        dns_client_id: $(dns_Client_Id)
        dns_client_secret: $(dns_Client_Secret)
        dns_subscription_id: $(dns_Subscription_Id)
        dns_zone_name: $(publicDnsZoneName)
        dns_resource_group: $(publicDnsZoneResourceGroup)
        admin_ssh_key_path: $(sshPubKey.secureFilePath)
        service_certificate_thumbprint: $(publicCertThumbprint)
        service_certificate_kv_url: $(publicCertKVSecretUrl)
        key_vault_id: $(publicCertKVResourceId)
      preSteps:
        - task: DownloadSecureFile@1
          name: sshPubKey
          displayName: Download SSH Public Key
          inputs:
            secureFile: $(sshKeyName)
        - task: PowerShell@2
          inputs:
            targetType: inline
            pwsh: true
            script: |
              Write-Host "##vso[task.setvariable variable=infra_arm_service_connection]$(infra_arm_service_connection_dev)"
              Write-Host "##vso[task.setvariable variable=publicCertKVSecretUrl]$(publicCertKVSecretUrl_dev)"
              Write-Host "##vso[task.setvariable variable=publicCertKVResourceId]$(publicCertKVResourceId_dev)"
