variables:
  - group: vh-wowza
  - group: vh-infra-dev
  - group: vh-infra-prod

trigger:
  branches:
    include:
    - master
    - release/*
    - hotfix/*

pr:
  branches:
    include:
    - master

stages:
  - template: pipeline/vh-terraform.yml
    parameters:
      deploymentResource: vh_wowza
      serviceConnections:
        ${{ if or(eq('Dev', parameters.environment),eq('Demo', parameters.environment)) }}:
          arm: $(infra_arm_service_connection_dev)
        ${{ if or(eq('Preprod', parameters.environment),eq('Prod', parameters.environment)) }}:
          arm: $(infra_arm_service_connection_prod)
        dns: $(infra_arm_service_connection_prod)
      tf_params:
        dns_tenant_id: $(dns_Tenant_Id)
        dns_client_id: $(dns_Client_Id)
        dns_client_secret: $(dns_Client_Secret)
        dns_subscription_id: $(dns_Subscription_Id)
        dns_zone_name: $(publicDnsZoneName)
        dns_resource_group: $(publicDnsZoneResourceGroup)
        admin_ssh_key_path: $(sshPubKey.secureFilePath)
        service_certificate_thumbprint: $(publicCertThumbprint)
        ${{ if eq('Dev', parameters.environment) }}:
          service_certificate_kv_url: $(publicCertKVSecretUrl_dev)
          key_vault_id: $(publicCertKVResourceId_dev)
        ${{ if eq('Demo', parameters.environment) }}:
          service_certificate_kv_url: $(publicCertKVSecretUrl_demo)
          key_vault_id: $(publicCertKVResourceId_demo)
        ${{ if eq('Preprod', parameters.environment) }}:
          service_certificate_kv_url: $(publicCertKVSecretUrl_preprod)
          key_vault_id: $(publicCertKVResourceId_preprod)
        ${{ if eq('Prod', parameters.environment) }}:
          service_certificate_kv_url: $(publicCertKVSecretUrl_prod)
          key_vault_id: $(publicCertKVResourceId_prod)
      preSteps:
        - task: DownloadSecureFile@1
          name: sshPubKey
          displayName: Download SSH Public Key
          inputs:
            secureFile: $(sshKeyName)
