parameters:
  name:
  workingDirectory: $(system.defaultWorkingDirectory)
  vmImage: ""
  environments: []

jobs:
- ${{ each deployment in parameters.environments }}:
  - deployment: ${{ parameters.name }}

    pool:
      vmImage: ${{ parameters.vmImage }}

    environment: ${{ deployment.name }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            clean: true

          - task: TerraformInstaller@0
            displayName: Install Terraform 0.13.2
            inputs:
              terraformVersion: 0.13.2

          - template: terraform-deploy.yml
            parameters:
              workingDirectory: ${{ parameters.workingDirectory }}
              storageAccount: ${{ deployment.storageAccount }}
              environment: ${{ deployment.name }}
              serviceConnections: ${{ deployment.serviceConnections }}
              tf_params: ${{ deployment.tf_params }}
              preSteps: ${{ deployment.preSteps }}
              postSteps: ${{ deployment.postSteps }}
