parameters:
  - name: baseAgent
    type: string
    default: Ubuntu-16.04

  - name: deploymentResource
    type: string

  - name: serviceConnections
    type: object

  - name: tf_params
    type: object

  - name: preSteps
    type: stepList
    default: []

stages:
  - stage: Plan_Dev_Environments
    jobs:
    - job: Dev_Plan
      pool:
          vmImage: ${{parameters.baseAgent}}

      variables:
        - group: vh-infra-dev
        - name: environment
          value: dev

      steps:
      - checkout: self
        clean: true

      - ${{ parameters.preSteps }}

      - template: terraform-plan.yml
        parameters:
          storageAccount: $(infra_storage_account_dev)
          environment: $(environment)
          serviceConnections: ${{ parameters.serviceConnections }}
          tf_params: ${{ parameters.tf_params }}

  - stage: Deploy_Dev_Environments
    condition: and(succeeded(), or(startsWith(variables['Build.SourceBranch'], 'refs/heads/master')))
    dependsOn:
      - Plan_Dev_Environments
    jobs:
      - template: terraform-deployment.yml
        parameters:
          name: ${{ parameters.deploymentResource }}
          vmImage: ${{parameters.baseAgent}}

          environments:
            - name: dev
              storageAccount: $(infra_storage_account_dev)
              serviceConnections: ${{ parameters.serviceConnections }}
              tf_params: ${{ parameters.tf_params }}
              preSteps: ${{ parameters.preSteps }}

  - stage: Plan_Demo_Environments
    dependsOn:
      - Plan_Dev_Environments
    jobs:
    - job: Demo_Plan
      pool:
          vmImage: ${{parameters.baseAgent}}

      variables:
        - group: vh-infra-dev
        - name: environment
          value: demo

      steps:
      - checkout: self
        clean: true

      - ${{ parameters.preSteps }}

      - template: terraform-plan.yml
        parameters:
          storageAccount: $(infra_storage_account_dev)
          environment: $(environment)
          serviceConnections: ${{ parameters.serviceConnections }}
          tf_params: ${{ parameters.tf_params }}

  - stage: Deploy_Demo_Environments
    condition: and(succeeded(), or(startsWith(variables['Build.SourceBranch'], 'refs/heads/master')))
    dependsOn:
      - Plan_Demo_Environments
    jobs:
      - template: terraform-deployment.yml
        parameters:
          name: ${{ parameters.deploymentResource }}
          vmImage: ${{parameters.baseAgent}}

          environments:
            - name: demo
              storageAccount: $(infra_storage_account_dev)
              serviceConnections: ${{ parameters.serviceConnections }}
              tf_params: ${{ parameters.tf_params }}
              preSteps: ${{ parameters.preSteps }}

  - stage: Plan_Preprod_Environments
    dependsOn:
      - Plan_Dev_Environments
    jobs:
    - job: Preprod_Plan
      pool:
          vmImage: ${{parameters.baseAgent}}

      variables:
        - group: vh-infra-prod
        - name: environment
          value: preprod

      steps:
      - checkout: self
        clean: true

      - ${{ parameters.preSteps }}

      - template: terraform-plan.yml
        parameters:
          storageAccount: $(infra_storage_account_prod)
          environment: $(environment)
          serviceConnections: ${{ parameters.serviceConnections }}
          tf_params: ${{ parameters.tf_params }}

  - stage: Deploy_Preprod_Environments
    condition: and(succeeded(), or(startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')))
    dependsOn:
      - Plan_Preprod_Environments
    jobs:
      - template: terraform-deployment.yml
        parameters:
          name: ${{ parameters.deploymentResource }}
          vmImage: ${{parameters.baseAgent}}

          environments:
            - name: preprod
              storageAccount: $(infra_storage_account_prod)
              serviceConnections: ${{ parameters.serviceConnections }}
              tf_params: ${{ parameters.tf_params }}
              preSteps: ${{ parameters.preSteps }}


  - stage: Plan_Prod_Environments
    dependsOn:
      - Plan_Dev_Environments
    jobs:
    - job: Prod_Plan
      pool:
          vmImage: ${{parameters.baseAgent}}

      variables:
        - group: vh-infra-prod
        - name: environment
          value: prod

      steps:
      - checkout: self
        clean: true

      - ${{ parameters.preSteps }}

      - template: terraform-plan.yml
        parameters:
          storageAccount: $(infra_storage_account_prod)
          environment: $(environment)
          serviceConnections: ${{ parameters.serviceConnections }}
          tf_params: ${{ parameters.tf_params }}

  - stage: Deploy_Prod_Environments
    condition: and(succeeded(), or(startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')))
    dependsOn:
      - Plan_Prod_Environments
      - Deploy_Preprod_Environments
    jobs:
      - template: terraform-deployment.yml
        parameters:
          name: ${{ parameters.deploymentResource }}
          vmImage: ${{parameters.baseAgent}}

          environments:
            - name: prod
              storageAccount: $(infra_storage_account_prod)
              serviceConnections: ${{ parameters.serviceConnections }}
              tf_params: ${{ parameters.tf_params }}
              preSteps: ${{ parameters.preSteps }}
